return {
	Aimbot = {
		AimMethod = "Mouse",
		AimStyle = "Linear",
		AimTargetting = "Closest To Crosshair",
	},
	Visuals = {},
	Settings = {
		MenuKeybind = "Z",
		RaycastOrigin = "Camera",
		StreamMode = false,
		ShowWatermark = false,
		ShowKeybinds = false,

		EntityLogs = {
			Enabled = false,
			PlaySoundOnLog = false,
			SoundToPlay = nil,
			Types = {
				Added = false,
				Removed = false,
				Hit = false,
				Killed = false,
			},
		},

		Hitmarkers = {
			Enabled = false,
			AnimateHitmarker = false,
			RotationSpeed = 1,
			HitmarkerSound = false,
			HitmarkerSoundVolume = 0.3,
			SoundToPlay = nil,
		},
	},
}
